### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by barrar** [clinew/2048#13]
32   16    4    2 
        16    4    .    . 
         4    .    .    . 
         2    .    .    . 
     > down
    Segmentation fault: 11
compiled on Yosemite......

Crash report: http://pastebin.com/raw.php?i=sF6EzAB0

**Comment by clinew** [comment]
Hi,

This was found and fixed in a different branch that hasn't yet been merged to main; I got this pesky "job" thing that eats up most of my time ;)

I'm going to leave this open until I take the time to integrate that branch into main.

Thank you,
Wade

**Comment by clinew** [comment]
Fixed and updated.
